### ISSUE TITLE
Nice program

### ISSUE THREAD

**Issue by hydranix** [hazardousparticle/rainbow510#1]
I borrowed some of the code from Rainbow510 to write my own small keyboard class, could I get your permission to be free from the license you're using?

**Comment by hazardousparticle** [comment]
sure, as long as its not a commercial project. also please acknowledge in a comment where you got the code and provide me a link to your projects repository.

**Comment by hydranix** [comment]
Awesome, Here's the project so far, planning to remove the libusb with ioctls or similar aslternative.
https://github.com/hydranix/G510_Linux
